import { StyleSheet } from 'react-native';
import { lightColors } from '../context/ThemeContext';

export const makeStyles = (colors: typeof lightColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: 80,
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 4,
    color: colors.title,
  },
  subtitle: {
    fontSize: 13,
    color: colors.subtitle,
    marginBottom: 20,
  },
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cardCompleted: {
    backgroundColor: colors.cardCompleted,
  },
  emoji: {
    fontSize: 24,
    marginRight: 12,
  },
  name: {
    flex: 1,
    fontSize: 16,
    color: colors.text,
  },
  nameCompleted: {
    textDecorationLine: 'line-through',
    color: colors.textCompleted,
  },
  check: {
    fontSize: 20,
  },
  form: {
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  input: {
    borderBottomWidth: 1,
    borderBottomColor: colors.inputBorder,
    paddingVertical: 8,
    fontSize: 16,
    marginBottom: 12,
    color: colors.input,
  },
  emojiLabel: {
    fontSize: 14,
    color: colors.subtitle,
    marginBottom: 8,
  },
  emojiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  emojiOption: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: colors.emojiOptionBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emojiSelected: {
    backgroundColor: colors.emojiSelectedBg,
    borderWidth: 2,
    borderColor: colors.emojiSelectedBorder,
  },
  emojiOptionText: {
    fontSize: 24,
  },
  btnConfirm: {
    backgroundColor: colors.btnConfirm,
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
  },
  btnConfirmText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  btnAdd: {
    position: 'absolute',
    bottom: 32,
    right: 24,
    backgroundColor: colors.btnAdd,
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  btnAddText: {
    color: '#fff',
    fontSize: 32,
    lineHeight: 36,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
    marginTop: 80,
  },
  emptyEmoji: {
    fontSize: 64,
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 8,
    textAlign: 'center',
    color: colors.title,
  },
  emptySubtitle: {
    fontSize: 15,
    color: colors.subtitle,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 8,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 26,
  },
  btnCancel: {
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  btnCancelText: {
    color: colors.subtitle,
    fontSize: 16,
  },
});